### ISSUE TITLE
Shouldn't Builder::body take self instead of &self?

### ISSUE THREAD

**Issue by pyfisch** [carllerche/http#106]
The only way to "use" a request/response builder is to call `body(some_body_data)` on it and create a message. The documentation on `body` is very explicit that this must be called once. But still the `body` signature is `&mut self` and not `self` as I'd expect. The docs already state that it "consumes" the builder, so why not turn the runtime panic to compile time errors if the method is called multiple times?

**Comment by alexcrichton** [comment]
The consumption here is a runtime check and `&mut self` is taken for ergonomics to easily chain methods. Thanks for the report though!

**Comment by pyfisch** [comment]
No, thank you for the explanation!

Maybe this kind of builder can be added to the [API guidelines](https://rust-lang-nursery.github.io/api-guidelines/type-safety.html#builders-enable-construction-of-complex-values-c-builder)?
