### ISSUE TITLE
TryFrom Parts for Uri has a Error type that can never occur

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/http#112]
The current implementation has `type Error = InvalidUri`, but this can never occur.

If we decide that #96 should be changed or removed, then this could be updated to correctly return an `InvalidUri` error.

If not, we might want to consider that a `From<T>` will likely end up in a `TryFrom<T> where Error = !` blanket impl. Can we have some uninhabited type in convert.rs as the `Error`, and then alias it to bang or something later?

**Comment by carllerche** [comment]
Handled by #114

**Comment by carllerche** [comment]
Fixed by #114
