### ISSUE TITLE
First impressions tracking issue

### ISSUE THREAD

**Issue by steveklabnik** [carllerche/http#45]
Using my day off to build a little HTTP server on top of the stdlib and http; Here's some issues @ashleygwilliams and I are finding. I'm not suggesting it _has_ to be this way, mind you, just things to consider.

- [ ] https://github.com/steveklabnik/simple-server/issues/3
- [ ] https://github.com/steveklabnik/simple-server/issues/2

**Comment by carllerche** [comment]
I'm going to assume this is resolved now.
