### ISSUE TITLE
HeaderMapKey implementation for String/str panics

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/http#72]
The docs show using strings as keys, and with it being the most "ergonomic" way, people will probably default to using it everywhere. Unfortunately, a string is not always a valid header name, and because of this, the `HeaderMapKey` implementation panics if it is invalid. 

This could lead to people uniformly just using strings, and then being surprised and upset when their server panics because of an illegal string. Of course, it's better to have panicked than to allow the damaging header name through, but users certainly would not have expected it. Should we remove the impl for `String`/`str`, so that users realize that `HeaderName::try_from(str).unwrap()` can panic?

**Comment by alexcrichton** [comment]
One possible alternative which may work is to only have `HeaderMapKey for &'static str` in the sense that it requires a string literal (albeit not the *only* source of `&'static str). It truly is a programmer error to have an invalid string literal as a header map key!

**Comment by seanmonstar** [comment]
That sounds nice to me! If we do that, is the error message at all obvious when a user doesn't supply a static string?

**Comment by carllerche** [comment]
This PR is replaced by #86?

**Comment by seanmonstar** [comment]
Closed by #86.
