### ISSUE TITLE
Ability to set Content-Encoding: gzip for files like .svgz

### ISSUE THREAD

**Issue by Mardeg** [carllerche/http#89]
How would an API to allow this look?

**Comment by carllerche** [comment]
I don't understand the question. You can set the `Content-Encoding` header to any value.

**Comment by Mardeg** [comment]
Okay, to reword it: A mechanism to _prevent_ a file like .svgz being served _without_ sending the associated Content-Encoding header, because not doing so (at least in Firefox) fails to render the SVG.

**Comment by pyfisch** [comment]
No. You are responsible to set correct headers for the body data. Higher level abstractions may offer a mechanism to prevent sending wrong headers for svgz files.

**Comment by carllerche** [comment]
Ah yes, this is outside the scope of the `http` crate and should be enforced by clients / servers that use the `http` crate.
