### ISSUE TITLE
Should `HeaderMap` at the root be a type alias instead of a re-export?

### ISSUE THREAD

**Issue by carllerche** [carllerche/http#90]
Since the most common usage of `HeaderMap<T>` is w/ `HeaderValue`, should the root re-export be a type def instead?

```rust
pub type HeaderMap = header::HeaderMap<header::HeaderValue>;
```

**Comment by seanmonstar** [comment]
I believe it should probably be a type alias, yes.

**Comment by pyfisch** [comment]
When is header map used with a different type? For typed headers?

**Comment by seanmonstar** [comment]
Within `http`, it's not. It's used for convenience in some tests, and we thought it might be useful for hpack, or something like hyper's typed headers.

I have a slight worry in back of my mind that it might cause unnecessary problems...

**Comment by carllerche** [comment]
I originally used it w/ a different `T` to implement HPACK encoding. I since stopped in favor of a custom structure that was more efficient.

IMO it is generally useful as it is a map that is optimized for header names... 

Another option would be to set a default for `T == HeaderValue`.

**Comment by alexcrichton** [comment]
I think I'd probably personally be in favor of a default type parameter here (sort of like libstd's `HashMap` does with the hasher) or jettisoning the generic if we dont otherwise have a use case for it.

**Comment by carllerche** [comment]
@alexcrichton I actually am going to use it to configure the hpack encoder. Basically, have per header field configurations, for example, never insert "foo" into the table.

**Comment by carllerche** [comment]
I think that I'd be OK with a default, though that would sometimes cause problems w/ the type inferencer?

**Comment by alexcrichton** [comment]
Ah ok then yeah I'd be in favor of a default then. To get type inference to work out it typically requires:

```rust
impl HeaderMap {
   pub fn new() -> HeaderMap { ... }
}

impl<T> HeaderMap<T> {
    pub fn get(...)
    ...
}
```

That is, the `new` constructor hard-wires the defaults and everything else is generic.
