### ISSUE TITLE
Is uri::Parts -> Uri fallible?

### ISSUE THREAD

**Issue by carllerche** [carllerche/http#96]
There currently is an `Into` implementation, but I believe that there may be be error cases. If so, the impl should be removed.

**Comment by seanmonstar** [comment]
Currently, the error cases hit `assert`s. This makes sense if you've received a `Parts` from an existing `Uri`... Is that supposed to be the **only** way you would have gotten one, anyways?

**Comment by carllerche** [comment]
No, h2 constructs a `Uri` from `Parts`. It seems like this should be switched to be fallible.
