### ISSUE TITLE
Make all "try from" functions consistently named

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/http#98]
For instance, there is:

- `Method::from_bytes`
- `HeaderName::from_bytes`
- `StatusCode::from_u16`

vs

- `HeaderValue::try_from_bytes`
- `Uri::try_from_shared`

**Comment by JJayet** [comment]
@seanmonstar Hi, I've started working on this.

I initially wanted to prefix `try_` every method which returns a Result<T, E> but looking at [Rust source files](https://github.com/rust-lang/rust/blob/ddaab61101e48f0a58ce176b5a6aff11ae36c986/src/libcore/str/mod.rs#L98), it would be inconsistant so I'm now inching the other way around.

What do you think? Should we remove every `try_`?

**Comment by seanmonstar** [comment]
Yea, I filed this as an issue to allow discussion on exactly *how* we should be consistent.
